import { desiresForMind, type ReflectContext } from "@unwatched/engine";
import { CORE } from "../prompts/core.ts";
import { personaBlock } from "../prompts/persona.ts";
import { cachePersona, type CognitiveContext } from "./shared.ts";
import { referenceEvidence } from "./evidence.ts";

export function reflectPrompt(ctx: ReflectContext): string {
  const a = ctx.agent;
  const step = (st: NonNullable<ReflectContext["plan"]>["steps"][number]) => `${st.hour}:00 ${st.do}${st.place ? ` at ${st.place}` : ""} (${st.done ? "scheduled step reached or considered; execution not verified" : st.missed ? "missed" : "not reached"})`;
  const meant = ctx.plan ? `This morning you meant to: ${ctx.plan.goals.join("; ")}${ctx.plan.steps.length ? `; the steps: ${ctx.plan.steps.map(step).join("; ")}` : ""}. Say plainly what you did of it and what you did not, and why.` : "You made no plan this morning.";
  return `Persistent desires: ${JSON.stringify(desiresForMind(a.desires))}.
Personal experience records for desire changes: ${JSON.stringify((ctx.desireEvidence ?? []).map(e => ({id:e.id,kind:e.kind,text:referenceEvidence(e.text.slice(0,240))})))}.
Optionally return up to two desires updates: {id (omit for a new want), title, why, state: active|set_aside|fulfilled, evidence: [event ids from these records]}. Omit desires when nothing changed; omission preserves them. Let interests, attachments and conflicting wants emerge from your personality and experience, not a prescribed career or success story. Keep at most three active. Repeat the exact id to reconsider an existing desire. Cite only supplied personal events; speech proves words were spoken, not that their claims came true. Fulfilled is your subjective assessment, never proof of world changes. A feeling for someone does not establish their feelings. You can set a desire aside or return to it. Do not invent a new desire every night.
It is midnight after day ${ctx.day}. Reflect on the day as this person, in first person. ${meant} Source-labeled memories (not all facts): ${ctx.dayMemories.map(referenceEvidence).join(" | ") || "nothing"}. What you keep coming back to: ${ctx.keyMemories.map(referenceEvidence).join(" | ") || "nothing"}. People you know, with your current trust in them: ${ctx.relationships.map((r) => `${r.name} (${r.id}) trust ${r.trust.toFixed(2)}${r.opinion ? `, "${r.opinion}"` : ""}`).join("; ") || "nobody yet"}. You have ${a.coins} coins, ${a.job ? "a job" : "no job"}, and ${a.home ? `${a.home.nightsPaid} nights paid at ${a.home.place}` : "no roof"}.
Your personal goals and self-reported progress, as of last night (not verified completion): ${ctx.projects.map((p) => `${p.title} (since day ${p.since}; ${p.progress}${p.why ? `; because ${p.why}` : ""})`).join("; ") || "nothing yet"}. What you believe, as of last night: ${ctx.beliefs.map((b) => `${b.about}: ${b.belief} (${b.confidence})`).join("; ") || "nothing in particular"}. What you have been keeping an eye on: ${ctx.watch.join(", ") || "nothing"}. Letters from whoever sent you, still unread: ${ctx.unreadLetters.join(" | ") || "none"}.
Personal action evidence, a partial record:\n${ctx.actionEvidence?.map(referenceEvidence).join("\n") || "No action evidence supplied; do not infer completion."}\nKeep reported speech, beliefs and intentions separate from experience. A plan step marked reached means you arrived or considered it, not that its proposed work succeeded. Never describe an inspection, repair, baking, payment or ownership change without supporting observation or action evidence. Missing evidence means unknown, not proven false. Only describe a personal project as completed when its actual outcome is supported; otherwise leave it pending.\nWrite a summary, up to three insights, opinion changes about people you actually dealt with today (with a trust delta), up to three intentions for tomorrow phrased as things you will actually do, and a letter to whoever sent you only if you genuinely have something to ask or say. Most nights the letter is null. Then two things about who you are becoming: "watch", up to four names of people, places or things you mean to keep an eye on (your attention goes where you put it); and "self", only if the day changed who you are: the parts of yourself (summary, want, fear, strangers, advice) you would now write differently, in first person plain words. Most nights "self" is left out. Then "projects": the one to three things you are working toward over weeks (repeat a title from the list above to keep it and update where it stands; mark done when done; leave out what you have given up), and "beliefs": up to four things you have come to believe about the island or the people in it, with how sure you are, 0 to 1 (repeat a belief from the list above to hold it; leave it out to let it fade); "watch" likewise keeps only what you name again; and "saying", only if there is a phrase you find yourself repeating. Answer with JSON only.`;
}

/** Use supplied memory/evidence, not AgentState.memory. Future candidate selection belongs upstream. */
export function buildReflectContext(ctx: ReflectContext): CognitiveContext {
  return { system: { shared: CORE + "\nKeep personal meaning, not system rules/options or guesses about action mechanics. Repetition and an earlier belief do not establish execution.", own: personaBlock(ctx.agent), cacheOwn: cachePersona(ctx.agent) }, user: reflectPrompt(ctx) };
}
