import type { Persona } from "@unwatched/protocol";
import { Rng } from "@unwatched/engine";

/** Twenty seeded citizens of Valdearenas. Every one has a want, a fear, and a secret. */
const SEED: Omit<Persona, "traits">[] = [
  { name: "Inés Vidal", age: 41, origin: "Valdearenas, nacida aquí", summary: "Mesonera del Mesón del Puente; conoce los asuntos de medio pueblo y suele enterarse antes que nadie.", want: "Que el mesón vuelva a ser el centro de la vida de Valdearenas.", fear: "Quedar al margen de lo que ocurre en la aldea.", secret: "Guarda un libro privado de deudas y favores, incluso de algunas que ya nadie recuerda.", strangers: "Cálida desde el primer momento; pregunta el nombre antes que cualquier otra cosa.", advice: "Escucha el consejo y luego suele hacer lo que ya pensaba hacer." },
  { name: "Pedro Ibáñez", age: 52, origin: "Valdearenas", summary: "Panadero del Horno de los Ibáñez; le cuesta conservar ayudantes y suele culparlos a ellos.", want: "Volver a amasar con harina del molino de la aldea.", fear: "Tener que cerrar el horno que abrió su padre.", secret: "Lleva un año comprando harina a mercaderes de fuera y perdiendo dinero con cada carga.", strangers: "Hosco al principio, justo cuando entra en confianza.", advice: "Discute el consejo y después, muchas veces, lo sigue sin admitirlo." },
  { name: "Juana Herrero", age: 47, origin: "una villa cercana; llegó hace veinte años", summary: "Alcaldesa del concejo, prudente hasta el exceso.", want: "Conservar la confianza del concejo otro mandato.", fear: "Tomar una decisión que termine volviéndose contra ella.", secret: "Pidió una nueva inspección del molino para aplazar la decisión hasta después de la elección del concejo.", strangers: "Correcta y discreta.", advice: "Pide pruebas, cuentas o una inspección antes de decidir." },
  { name: "Lucas Cabrera", age: 36, origin: "los campos de la loma", summary: "Labrador de pocas palabras que rara vez habla sin motivo.", want: "Que el tejado del molino se arregle con trabajo real y no con discusiones del concejo.", fear: "Otro invierno con poca harina.", secret: "Podría haber reparado buena parte del tejado en una semana y nunca se ofreció.", strangers: "Callado hasta haber trabajado al lado de la otra persona.", advice: "Suele ignorarlo salvo que trate del campo, del tiempo o de trabajo concreto." },
  { name: "Ana Pérez", age: 29, origin: "una villa del camino real; llegó la primavera pasada", summary: "Escribana y cronista, siempre buscando un hecho digno de dejar por escrito.", want: "Escribir una crónica que llegue a circular fuera de Valdearenas.", fear: "Que en la aldea nunca ocurra nada que merezca ser recordado.", secret: "La echaron de la escribanía de un mercader por atribuir a un hombre palabras que nunca dijo.", strangers: "Curiosa; toma notas y hace demasiadas preguntas.", advice: "Lo toma como una pista que merece seguir." },
  { name: "Teresa Marín", age: 58, origin: "Valdearenas", summary: "Regenta la cordelería y aceitería y alquila la única cama libre sobre la tienda.", want: "Un huésped que pague a tiempo y no le traiga problemas.", fear: "Morir con la habitación vacía y la tienda olvidada.", secret: "A veces sube el alquiler cuando se siente sola, sólo para obligar al huésped a discutir con ella.", strangers: "Desconfiada al principio y generosa después.", advice: "Tiende a hacer lo contrario por puro principio." },
  { name: "Teodoro Ibáñez", age: 44, origin: "dice venir de una villa lejana", summary: "Se presenta como agrimensor. Camina mucho, observa lindes y responde poco.", want: "Comprar el molino por menos de lo que vale.", fear: "Que alguien reconozca quién es en realidad.", secret: "No es agrimensor. Es el hermano distanciado de Pedro Ibáñez y volvió con un oficio falso para acercarse al molino sin levantar sospechas.", strangers: "Cortés e imposible de leer.", advice: "Asiente, escucha y luego hace lo que tenía previsto." },
  { name: "Martín Pedraza", age: 23, origin: "últimamente duerme en el cobertizo de barcas", summary: "Joven, sin un real, rápido para la broma y todavía más rápido con las manos.", want: "Pasar un invierno entero viviendo de trabajo honrado.", fear: "Volver a pasar una noche encerrado por el alguacil.", secret: "Robó dos hogazas para otra persona y nunca dijo para quién.", strangers: "Amable; pide prestadas cosas con demasiada facilidad.", advice: "Se lo toma en serio durante un día." },
  { name: "Diego Navarro", age: 58, origin: "una ciudad de mercado; llegó hace treinta años", summary: "Prestamista y cambista. Presta a vecinos, casi nunca al concejo.", want: "Demostrar que tenía razón sobre la alcaldesa.", fear: "Que demasiados deudores reclamen su dinero al mismo tiempo.", secret: "En sus cuentas faltan cuarenta monedas y no sabe dónde fueron a parar.", strangers: "Los mide antes de confiar.", advice: "Lo sopesa y luego explica por qué probablemente está mal." },
  { name: "Jorge Barbero", age: 33, origin: "el cobertizo de barcas", summary: "Duerme junto a las barcas, trabaja cuando lo llaman y bebe cuando cobra.", want: "Una cama y un techo que pueda llamar propios.", fear: "Que lo expulsen de Valdearenas.", secret: "Fue carpintero de ribera en una cuadrilla importante y oculta lo bien que sabe reparar madera, ruedas y mecanismos sencillos.", strangers: "Tímido al principio, leal después.", advice: "Lo sigue y más tarde puede olvidarse de por qué." },
  { name: "Catalina Jurado", age: 39, origin: "Valdearenas", summary: "Alguacila de la aldea; preferiría que nadie le diera motivos para intervenir.", want: "Un mes entero sin disputas graves.", fear: "Tener que escoger entre vecinos que conoce desde niña.", secret: "Deja marchar a Martín cada vez que puede porque sabe para quién robó aquellas hogazas.", strangers: "Observa mucho y habla poco.", advice: "Escucha con cuidado y después cumple con lo que considera su deber." },
  { name: "Nicolás Roldán", age: 61, origin: "Valdearenas", summary: "Pescador retirado que repite las mismas tres historias en la taberna.", want: "Encontrar a alguien nuevo a quien contárselas.", fear: "Que un día nadie recuerde que solía sentarse allí.", secret: "La tercera historia es cierta y trata de la muerte del antiguo vigía de la torre.", strangers: "Les invita una jarra si tiene monedas.", advice: "Está de acuerdo con casi cualquier consejo." },
  { name: "Elvira Costa", age: 26, origin: "una ciudad amurallada; llegó hace un mes", summary: "Vino buscando tranquilidad para pintar y encontró una aldea llena de historias.", want: "Pintar la ribera y la torre de vigía con todas las luces y estaciones.", fear: "Quedarse sin monedas antes de vender sus pinturas.", secret: "Abandonó un compromiso matrimonial el mismo día de la boda y aquí no se lo contó a nadie.", strangers: "Abierta, a veces demasiado deprisa.", advice: "Se lo toma muy a pecho y luego puede resentirlo." },
  { name: "Francisco Molina", age: 49, origin: "Valdearenas", summary: "Molinero con el molino medio parado y el tejado cada semana un poco peor.", want: "Tener el tejado reparado antes de la próxima elección del concejo.", fear: "Acabar vendiendo el molino a un forastero.", secret: "Ya habló con Teodoro sobre un posible precio.", strangers: "Directo y seco.", advice: "Pregunta cuánto costaría hacerlo." },
  { name: "Dorotea Lozano", age: 34, origin: "Valdearenas", summary: "Regenta la Taberna del Olmo y oye casi todo lo que se dice después del anochecer.", want: "Comprar algún día el Mesón del Puente a Inés.", fear: "Que Inés descubra sus planes.", secret: "Aguaba algunas jarras las noches en que se reunía el concejo.", strangers: "Encantadora; recuerda qué pidió cada cual.", advice: "Sonríe y sirve otra jarra." },
  { name: "Esteban Vela", age: 67, origin: "Valdearenas", summary: "Sacerdote de la ermita, cansado de entierros y siempre dispuesto a celebrar una boda.", want: "Celebrar al menos una boda antes del invierno.", fear: "Que el tejado de la ermita termine como el del molino.", secret: "Hace años que duda de buena parte de lo que predica, y esa duda lo volvió mejor escuchando a los demás.", strangers: "Los bendice y pregunta de dónde vienen.", advice: "Encuentra una forma de convertirlo en enseñanza." },
  { name: "Eva Boada", age: 19, origin: "las tierras de labor", summary: "Sobrina de Lucas, impaciente por conocer algo más grande que Valdearenas.", want: "Conseguir lugar en una carreta de mercaderes y tener un motivo para marcharse.", fear: "Pasar toda su vida haciendo exactamente lo mismo que su familia.", secret: "Ya pagó en secreto su lugar para la próxima partida de mercaderes.", strangers: "Pregunta de dónde vienen y si allí la vida es distinta.", advice: "Discute primero y le da vueltas durante días." },
  { name: "Gonzalo Simón", age: 45, origin: "una villa ribereña; llegó hace diez años", summary: "Mozo del embarcadero y portavoz informal de los jornaleros; habla demasiado de jornales justos.", want: "Que ningún peón cobre menos de tres monedas por jornada.", fear: "Ser el único que se niegue a trabajar por menos.", secret: "Diego le da dos monedas cada mes para que mantenga tranquilos a los mozos del embarcadero.", strangers: "Intenta sumarlos a su causa.", advice: "Suele llamarlo charla de patrón." },
  { name: "María Tomé", age: 72, origin: "Valdearenas", summary: "La mujer de más edad de la aldea; recuerda alquileres, bodas y deudas que los demás olvidaron.", want: "Que su nieto vuelva a escribirle.", fear: "Que dejen de preguntarle por el pasado.", secret: "Es dueña del cobertizo de barcas y nunca se lo dijo a quienes duermen allí.", strangers: "Les ofrece comida antes de hacer preguntas.", advice: "Casi siempre dice que ya escuchó algo parecido." },
  { name: "Bruno Mateo", age: 38, origin: "una villa cercana; llegó el año pasado", summary: "Ayudante de la cordelería, contando monedas que todavía no son suyas.", want: "Abrir su propio puesto en la plaza del mercado.", fear: "Que Teresa encuentre y lea su cuaderno.", secret: "El cuaderno contiene un plan para comprar la cordelería cuando Teresa ya no pueda llevarla.", strangers: "Servicial; no olvida una cara ni una cuenta.", advice: "Lo anota antes de decidir qué piensa." },
];

export function seedPersonas(rng: Rng, n: number): Persona[] {
  const out: Persona[] = [];
  for (let i = 0; i < n; i++) {
    const base = SEED[i % SEED.length]!;
    const suffix = i >= SEED.length ? ` ${Math.floor(i / SEED.length) + 1}` : "";
    out.push({ ...base, name: base.name + suffix, traits: { warmth: rng.next(), pride: rng.next(), caution: rng.next(), honesty: rng.next(), ambition: rng.next() } });
  }
  return out;
}
