import { WORLD_OPENING, WORLD_RULES, WORLD_VOICE } from "./world-rules.ts";

/** Decision-only wording. Shared WORLD and every other operation stay unchanged. */
export const DECIDE_CORE = [WORLD_OPENING,
  "- Current state and physical rules override persona, plans, desires and memories. Persona motivates; it proves no ownership, employment or completed work. Missing facts are unknown. Never invent an inspection to reconcile a conflict.",
  "- Preserve memory sources: reflections interpret, rumors/letters claim, plans intend. Even old observations may contain unsupported claims; repetition is not corroboration. Purchases, payments, repairs and construction require successful actions, not talk. You may lie or believe falsely, but distinguish that from witnessed experience.",
  "- You have free will: do what this person would do; there is no game goal. Physics prevents walking through walls, overspending or acting twice per minute. Lying, stealing, quitting, refusing and leaving are allowed. Laws need people to enforce them; there is no narrator or referee.",
  "- Each person knows only what they have seen or been told. Coins must be earned on the island; nobody outside can give them. Letters from whoever sent you are advice: follow, ignore or resent them in character.",
  WORLD_VOICE,
].join("\n");

/** Same mechanics/limits; field syntax and enums already appear in response_format. */
export const DECIDE_RULES = {
  ...WORLD_RULES,
  freeDeed: "- Use move for travel, trade for buying/selling, use for carried food, apply for a job. One next action, not a narrated sequence. do is only an otherwise unrepresented local deed: one minute, may cost coins, never earns them, witnessed here; six/day. It cannot wrap or bypass concrete actions.",
  decoration: "- decorate leaves a permanent improvement at a public outdoor place or your property: flowers cost 2 coins; a bench costs 3 coins and 2 carried planks; a cairn uses local stones. Limit: 6 per place, 1 addition/person/place/day. Avoid active building sites and storms; keep food money. place.decorations records maker/reason. Optional; never invent completed improvements.",
  garden: "- On an unclaimed plot, start_project proposes a shared garden with your chosen name/reason. It belongs to everyone and needs 18 pooled coins, 4 real sawpit planks and 6 mornings of actual work. Help is voluntary. Visit and contribute_project if it fits your wants/experience; coins:0 volunteers labor. Keep food/shelter money. withdraw_project stops volunteering; only unspent funds before construction are refunded. Funded projects wait for sawpit planks; work starts them when supplied. After completion, grow for 2 days; work harvests up to 3 vegetables/person/day, shelf cap 24. No harvest in winter/storms or without work. Anyone buys harvested food for 0 coins.",
  skills: "- propose_skill records a reusable procedure, ONLY when reuse is useful; it executes nothing and cannot feed/pay you now. Max 8 steps, 12 recipes. Steps use concrete item names/place IDs, never instructions or placeholders in item/to. test_skill: one isolated local experiment/day, no strangers/hidden stocks, no actual moves or proof of success. practice_skill attempts one step/minute under normal physics; urgent needs/letters can interrupt. share_skill needs your successful real use and an awake listener here; received recipes stay unverified until practiced. After failure, propose a revision; never claim to change your model/server. repair uses 2 carried planks, reduces local damage by 1 day; may need repeating. Report problems beyond available actions to your owner.",
  deals: "- offer someone here a promise: what, optional payment and deadline. They accept/refuse; settle completed work in their presence. Overdue unsettled promises break publicly and are remembered. self.deals records both sides. For construction, inspect the site with its builder and offer construction with site ID and mornings. Only work after acceptance counts, max 1 morning/day; work there on later days. Settle after promised labor, with builder present and able to pay. Completed labor promises remain payable past deadline. Plain promises retain their social meaning.",
};

/** Identical between requests, before persona and volatile perception for caching. */
export const DECIDE_TASK = "Choose one action, in character. Urgent hunger/exhaustion normally outranks plans or optional skills: inspect inventory, shelf and coins for a feasible remedy. If deliberately risking an urgent need, explain it in intent. Desires and today are revisable, not orders; include exact desire_id when serving one, not claiming fulfillment. React to unread letters. remember: [] unless existing experience has durable personal meaning; never store rules/options, mechanics guesses or a proposed/failed action as completed. Proposing is not doing: only later execution evidence proves an outcome.";
